MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 3
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
  WARM_UP_ITERS: 2000
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ASPECT_RATIOS: (0.3, 0.5, 1) 
  RPN_ANCHOR_START_SIZE: 8 
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 64
  WIDTH_PER_GROUP: 4
  RES5_DILATION: 2
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: ./weights/X-101-64x4d.pkl #https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/FBResNeXt/X-101-64x4d.pkl
  DATASETS: ('coco_2014_train', )
  SCALES: (832,)
  MAX_SIZE: 1664
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 1024
  RPN_PRE_NMS_TOP_N: 12000  # Per FPN level
TEST:
  DATASETS: ('coco_2014_minival',)
  SCALE: 800
  MAX_SIZE: 1664
  NMS: 0.6
  RPN_NMS_THRESH: 0.8
  RPN_PRE_NMS_TOP_N: 12000  # Per FPN level
  RPN_POST_NMS_TOP_N: 4000
  BBOX_AUG: 
    ENABLED: False
    H_FLIP: True
    SCALE_H_FLIP: True
    ASPECT_RATIO_H_FLIP: True
    ASPECT_RATIOS: (0.25, 0.3, 0.5, 1,)
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.85
    SCORING_METHOD: IOU_AVG
  SOFT_NMS:
    ENABLED: True
    METHOD: linear
    SIGMA: 0.5
OUTPUT_DIR: .
